name = "cf-speedtest-v2"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-10"

# Disable `workers.dev` domain
workers_dev = false

[build]
command = "cargo install -q worker-build && worker-build --release"
