name = "cf-speedtest-v2"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-10"

# Disable `workers.dev` domain
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1

[build]
command = "cargo install -q worker-build && worker-build --release --package cf-speedtest-v2"
